apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-appbundle
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cicd
    name: in-cluster
  project: cicd-appbundle-project
  source:
    path: cicd-apps/
    repoURL: https://github.com/ADemesaA/demo-argocd.git
    targetRevision: HEAD
