apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-appbundle
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: cicd-apps/
    repoURL: https://github.com/ADemesaA/demo-argocd.git
    targetRevision: HEAD
