apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  destination:
    namespace: cicd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: global.hosts.domain
          value: demo.mx
        - name: global.edition
          value: ce
        - name: certmanager-issuer.email
          value: amado.demesaa@gmail.com
        - name: 'tcp.22'
          value: 'gitlab/mygitlab-gitlab-shell:22'
        - name: 'global.ingress.class'
          value: 'public'
        - name: nginx-ingress.enabled
          value: 'false'
        - name: certmanager.install
          value: 'false'
        - name: global.ingress.configureCertmanager
          value: 'false'
        - name: gitlab-runner.install
          value: 'false'
        - name: prometheus.install
          value: 'false'
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: 7.1.2
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
