apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: cicd
    server: https://kubernetes.default.svc
  project: cicd-appbundle-project
  source:
    helm:
      parameters:
        - name: controller.ingress.enabled
          value: 'true'
        - name: controller.ingress.hostName
          value: jenkins.demo.mx
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 4.12.1
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
