apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  destination:
    namespace: cicd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostRepo
          value: nexus.demo.mx
        - name: ingress.ingressClassName
          value: public
    chart: nexus-repository-manager
    repoURL: https://sonatype.github.io/helm3-charts/
    targetRevision: 57.0.0
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
